
// bookmark_create_response_message automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type BookmarkCreateResponseMessage struct {
    Bookmarked bool `json:"bookmarked"`
}
