
// bookmark_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type BookmarkCreate struct {
    TweetId string `json:"tweet_id"`
}
