
// bookmark_create_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type BookmarkCreateResponse struct {
    Data BookmarkCreateResponseMessage `json:"data"`
}
