
// Client automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    
    
    
    "github.com/apioo/sdkgen-go/v2"
    
    
    
    
)

type Client struct {
    internal *sdkgen.ClientAbstract
}

func (client *Client) Tweet() *TweetTag {
    return NewTweetTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Usage() *UsageTag {
    return NewUsageTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) User() *UserTag {
    return NewUserTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Bookmark() *BookmarkTag {
    return NewBookmarkTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Search() *SearchTag {
    return NewSearchTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Quote() *QuoteTag {
    return NewQuoteTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Trends() *TrendsTag {
    return NewTrendsTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Retweet() *RetweetTag {
    return NewRetweetTag(client.internal.HttpClient, client.internal.Parser)
}




func NewClient(baseUrl string, credentials sdkgen.CredentialsInterface) (*Client, error) {
	var client, err = sdkgen.NewClient(baseUrl, credentials)
    if err != nil {
        return &Client{}, err
    }

	return &Client{
		internal: client,
	}, nil
}

func Build(token string) (*Client, error) {
    var credentials = sdkgen.HttpBearer{Token: token}

    return NewClient("https://api.twitter.com", credentials)
}

func BuildAnonymous() (*Client, error) {
    var credentials = sdkgen.Anonymous{}

    return NewClient("https://api.twitter.com", credentials)
}
