
// Client automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    
    
    "github.com/apioo/sdkgen-go"
    
    
    
    
)

type Client struct {
    internal *sdkgen.ClientAbstract
}

func (client *Client) Tweet() *TweetTag {
    return NewTweetTag(client.internal.HttpClient, client.internal.Parser)
}




func NewClient(baseUrl string, credentials sdkgen.CredentialsInterface) (*Client, error) {
	var client, err = sdkgen.NewClient(baseUrl, credentials)
    if err != nil {
        return &Client{}, err
    }

	return &Client{
		internal: client,
	}, nil
}

func Build(token string) (*Client, error) {
    var credentials = sdkgen.HttpBearer{Token: token}

    client, err := NewClient("https://api.twitter.com", credentials)
    if err != nil {
        return &Client{}, err
    }

    return &Client {
        internal: client,
    }, nil
}

