
// error automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Error struct {
    Type string `json:"type"`
    Title string `json:"title"`
    Status int `json:"status"`
    Detail string `json:"detail"`
}

