
// fields automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Fields struct {
    MediaFields string `json:"media.fields"`
    PlaceFields string `json:"place.fields"`
    PollFields string `json:"poll.fields"`
    TweetFields string `json:"tweet.fields"`
    UserFields string `json:"user.fields"`
}

