
// like_response_message automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type LikeResponseMessage struct {
    Liked string `json:"liked"`
}
