
// like_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type LikeResponse struct {
    Data *LikeResponseMessage `json:"data"`
}
