
// trend automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Trend struct {
    TrendName string `json:"trend_name"`
    TweetCount int `json:"tweet_count"`
}

