
// TrendsTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

import (
    
    "encoding/json"
    "errors"
    "fmt"
    
    "io"
    "net/http"
    "net/url"
    
)

type TrendsTag struct {
    internal *sdkgen.TagAbstract
}



// GetByWoeid The Trends lookup endpoint allow developers to get the Trends for a location, specified using the where-on-earth id (WOEID).
func (client *TrendsTag) GetByWoeid(woeid string) (TrendCollection, error) {
    pathParams := make(map[string]interface{})
    pathParams["woeid"] = woeid

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/2/trends/by/woeid/:woeid", pathParams))
    if err != nil {
        return TrendCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return TrendCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return TrendCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return TrendCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data TrendCollection
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    return TrendCollection{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewTrendsTag(httpClient *http.Client, parser *sdkgen.Parser) *TrendsTag {
	return &TrendsTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
