
// tweet_create_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type TweetCreateResponse struct {
    Data *TweetCreateResponseMessage `json:"data"`
}
