
// tweet_media automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type TweetMedia struct {
    MediaIds []string `json:"media_ids"`
    TaggedUserIds []string `json:"tagged_user_ids"`
}
