
// tweet_details automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


import "time"
type TweetDetails struct {
    AuthorId string `json:"author_id"`
    ConversationId string `json:"conversation_id"`
    CreatedAt time.Time `json:"created_at"`
    EditHistoryTweetIds []string `json:"edit_history_tweet_ids"`
    Id string `json:"id"`
    InReplyToUserId string `json:"in_reply_to_user_id"`
    Text string `json:"text"`
}
