
// tweet_poll automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type TweetPoll struct {
    DurationMinutes int `json:"duration_minutes"`
    Options []string `json:"options"`
}

