
// tweet_delete_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type TweetDeleteResponse struct {
    Data *TweetDelete `json:"data"`
}

