
// tweet_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type TweetCreate struct {
    Id string `json:"id"`
    Text string `json:"text"`
}

