
// tweet_collection_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type TweetCollectionResponse struct {
    Data []TweetDetails `json:"data"`
}
