
// tweet_reply automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type TweetReply struct {
    ExcludeReplyUserIds []string `json:"exclude_reply_user_ids"`
    InReplyToTweetId string `json:"in_reply_to_tweet_id"`
}
