
// tweet_delete_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type TweetDeleteResponse struct {
    Data TweetDeleteResponseMessage `json:"data"`
}
