
// tweet_usage_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type TweetUsageResponse struct {
    Data *TweetUsage `json:"data"`
}
