
// tweet_create_response_message automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type TweetCreateResponseMessage struct {
    Id string `json:"id"`
    Text string `json:"text"`
}
