
// tweet_entity_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type TweetEntityResponse struct {
    Data TweetDetails `json:"data"`
}
