
// UsageTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type UsageTag struct {
    internal *sdkgen.TagAbstract
}



// GetTweets The Usage API in the Twitter API v2 allows developers to programmatically retrieve their project usage. Using thie endpoint, developers can keep a track and monitor of the number of Tweets they have pulled for a given billing cycle.
func (client *UsageTag) GetTweets() (TweetUsageResponse, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})

    u, err := url.Parse(client.internal.Parser.Url("/2/usage/tweets", pathParams))
    if err != nil {
        return TweetUsageResponse{}, err
    }

    u.RawQuery = client.internal.Parser.Query(queryParams).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return TweetUsageResponse{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return TweetUsageResponse{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return TweetUsageResponse{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response TweetUsageResponse
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return TweetUsageResponse{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return TweetUsageResponse{}, errors.New("the server returned an unknown status code")
    }
}



func NewUsageTag(httpClient *http.Client, parser *sdkgen.Parser) *UsageTag {
	return &UsageTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
