
// user automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type User struct {
    CreatedAt string `json:"created_at"`
    Id string `json:"id"`
    Name string `json:"name"`
    PinnedTweetId string `json:"pinned_tweet_id"`
    Username string `json:"username"`
}
